### ISSUE TITLE
Intermittant CI Failure

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1407]
The following test intermittently fails in CI; re-running usually clears the error. Any thoughts as to what we can do to improve this @jrwrigh?
```
        TEST fluids-py-smartsim_regression_framework
13:03:30 noether SmartSim[993423] ERROR Orchestrator failed during startup See /var/lib/gitlab-runner/builds/N8GCsqus/2/libceed/libCEED/tests/test_dir/test/database for details
Traceback (most recent call last):
  File "/var/lib/gitlab-runner/builds/N8GCsqus/2/libceed/libCEED/tests/junit.py", line 197, in <module>
    test_framework.setup()
  File "/var/lib/gitlab-runner/builds/N8GCsqus/2/libceed/libCEED/examples/fluids/smartsim_regression_framework.py", line 51, in setup
    self.exp.start(self.database)
  File "/home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/experiment.py", line 191, in start
    self._control.start(
  File "/home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/control/controller.py", line 95, in start
    self._launch(manifest)
  File "/home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/control/controller.py", line 323, in _launch
    self._launch_orchestrator(orchestrator)
  File "/home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/control/controller.py", line 384, in _launch_orchestrator
    self._orchestrator_launch_wait(orchestrator)
  File "/home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/control/controller.py", line 584, in _orchestrator_launch_wait
    raise SmartSimError(msg)
smartsim.error.errors.SmartSimError: Orchestrator failed during startup See /var/lib/gitlab-runner/builds/N8GCsqus/2/libceed/libCEED/tests/test_dir/test/database for details
make: *** [Makefile:678: junit-fluids-py-smartsim_regression_framework] Error 1
```

**Comment by jrwrigh** [comment]
Does the created `test_dir` get saved on CI? That will have log info about why it failed. Unfortunately I don't think there's a way to get that failure info other than through the log files from SmartSim.

**Comment by jeremylt** [comment]
I just checked - I could CD directly to the dir, though this is from a newer run so there isn't any error log here because it was overwritten.

```
jeth8984@noether:/var/lib/gitlab-runner/builds/N8GCsqus/2/libceed/libCEED/tests/test_dir/test/database$ cat orchestrator_0.out
----------- Running Command ----------
COMMAND: /home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/bin/redis-server /home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/config/redis.conf --loadmodule /home/jawr8143/SmartSimTestingSoftware/smartsim/smartsim/_core/lib/redisai.so --port 6780 --bind 127.0.0.1 --bind-source-addr 127.0.0.1
IPADDRESS: 127.0.0.1
NETWORK: lo
SMARTSIM_ORC_SHARD_INFO: {"name": "orchestrator_0", "hostname": "127.0.0.1", "port": 6780, "cluster": false}
--------------------------------------

--------------- Output ---------------


1543925:C 30 Nov 2023 10:01:52.665 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1543925:C 30 Nov 2023 10:01:52.665 # Redis version=7.0.5, bits=64, commit=1571907e, modified=0, pid=1543925, just started
1543925:C 30 Nov 2023 10:01:52.665 # Configuration loaded
1543925:M 30 Nov 2023 10:01:52.666 * Increased maximum number of open files to 50032 (it was originally set to 1024).
1543925:M 30 Nov 2023 10:01:52.666 * monotonic clock: POSIX clock_gettime
1543925:M 30 Nov 2023 10:01:52.666 # Warning: Could not create server TCP listening socket 127.0.0.1:6780: bind: Address already in use
1543925:M 30 Nov 2023 10:01:52.666 # Failed listening on port 6780 (TCP), aborting.
```

**Comment by jrwrigh** [comment]
Ah, ok. I think the issue is when we have multiple runners at the same time, then there's a conflict of the socket number for the database.

I guess we could try and check for open sockets, then use whatever one is open? Not sure how to execute that, but I can look into that.

**Comment by jedbrown** [comment]
Can you request port 0 and report what is assigned (see accepted answer)? https://unix.stackexchange.com/questions/55913/whats-the-easiest-way-to-find-an-unused-local-port

**Comment by jrwrigh** [comment]
Not sure what you mean by "report what is assigned... but don't close [the socket]", but I have an implementation in #1408 right now.
